apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-halal-place
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add-halal-place
  template:
    metadata:
      labels:
        app: add-halal-place
    spec:
      containers:
        - image: selmah/rso-project:add-halal-place-api-v1-05-01-2021
          name: add-halal-place
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://suleiman.db.elephantsql.com:5432/wgyzhvjo
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: wgyzhvjo
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: jvXTDZTYpQWoG_BfBUQDYp9uz5wBWvLD
          ports:
            - containerPort: 80
              name: server
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /health/live
#              port: server
#            initialDelaySeconds: 20
#            periodSeconds: 3
#            readinessProbe:
#              httpGet:
#                path: /health/ready
#                port: server
#              initialDelaySeconds: 20
#              periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: add-halal-place
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: server
  selector:
    app: add-halal-place